spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zdx1993/study-spring-cloud-config.git
          search-paths: repository
          username: 505707606@qq.com
          password: zdx3991@163.com

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/